
TYPE
	MainState_enum : 
		(
		MAIN_STATE_OFF,
		MAIN_STATE_INITIALIZE,
		MAIN_STATE_IDLE,
		MAIN_STATE_ENABLE_SECTIONS,
		MAIN_STATE_RUNNING,
		MAIN_STATE_STOPPING,
		MAIN_STATE_ERROR,
		MAIN_STATE_RESET
		);
END_TYPE
