
TYPE
	StateEnum : 
		(
		STSYSTEM_STATE_OFF,
		STSYSTEM_STATE_ENABLING,
		STSYSTEM_STATE_IDLE,
		STSYSTEM_STATE_RUN,
		STSYSTEM_STATE_STOPPED,
		STSYSTEM_STATE_ERROR,
		STSYSTEM_STATE_RESETTING
		);
END_TYPE
