
TYPE
	TargetControlState_enum : 
		(
		TARGET_STATE_WAIT_FOR_SHUTTLE,
		TARGET_STATE_SHUTTLE_PRESENT,
		TARGET_STATE_SET_MOTION_PARS,
		TARGET_STATE_RELEASE_SHUTTLE,
		TARGET_STATE_WAIT_FOR_RELEASE,
		TARGET_STATE_WAIT_FOR_CMD_RESET
		);
END_TYPE
