
TYPE
	MainState_enum : 
		(
		MAIN_STATE_OFF,
		MAIN_STATE_DISABLED,
		MAIN_STATE_ENABLE_SECTIONS,
		MAIN_STATE_RECOVER,
		MAIN_STATE_READY,
		MAIN_STATE_RUN,
		MAIN_STATE_STOP,
		MAIN_STATE_DISABLING,
		MAIN_STATE_ERROR,
		MAIN_STATE_RESET
		);
END_TYPE
